### PR TITLE
Add GenerateCSV to protobuf defiinition and regen files

### PR DESCRIPTION
**Pull request by emptyflash**

### CODE REVIEW

**Comment by immesys** [comment]
Do you think you could split this into multiple functions (for raw, aligned, unaligned) and give them descriptive names like `AlignedWindowsToCSV`. The number of parameters is a bit high for a user facing function. You can do the split by making this function private and making thin wrappers as public functions.

EDIT: it is ok to have a single writeCSV function on the endpoint. Just the public BTrDB functions should be more friendly.

Is there an advantage to taking a CSV writer rather than a io.Writer? What would the user do with the csv writer before or after calling this function?

**Comment by emptyflash** [comment]
I agree, I think passing in an enum parameter to indicate different behavior is a bit of an antipattern. I wasn't sure how far the bindings API should stray from the grpc API, so I followed it pretty closely.

I don't think there's any practical advantage of using a csv.Writer over io.Writer. I do think it makes the interface more clear; the types tell you what operations the `writeCsv` function can actually do to the underlying writer.

**Comment by immesys** [comment]
The thing is that a csv.Writer is a struct, not a generic interface (as an aside it should therefore be `*csv.Writer`). I would have to construct it specifically to pass to this function. I think its layer-punching to make the user do that. I would prefer either passing a filename or an io.Writer. The latter is more common (passing a filename is usually frowned upon because then you can't stream it or concatenate it).

**Comment by immesys** [comment]
Actually why don't you leave the current method public (with the *csv.Writer), and also add the new methods. That way if someone really wants to use tab separated values or whatever, they can use the underlying function.

**Comment by emptyflash** [comment]
Yeah that sounds pretty good. Lemme do that instead.

**Pull request closed without merging**
