### PR TITLE
Refactor helper funcs to file, add query tests

### PR DESCRIPTION
**Pull request by emptyflash**
In the process of writing these tests I found some of the helper functions in `corners_test.go` useful, so I refactored them out into their own file. Let me know if I should refactor the rest into this file.

I also added 4 tests, testing both windows queries with two scenarios, one where the data has a hole in the middle, and one checking the equality of flushed and unflushed data.

### CODE REVIEW

**Comment by immesys** [comment]
Does this test catch if there are missing stat windows? Or does it only check the correctness of windows that are actually returned?

**Comment by emptyflash** [comment]
For the data with holes it compares the statistics calculated from the raw points to the returned stat points. With the flushed/unflushed it just compares the results of the two queries.

**Comment by immesys** [comment]
But what if the returned statistical array is empty? The checkCorrect function won't catch that?

**Comment by immesys** [comment]
Haha, that's not what I meant. That's just one specific case. Here, let me explain.

Say I query for data over a day, and there is actually a full days worth of data but the response is served only from fully committed data and the PQM data is not being merged, then I will get back a few records from the start of the day but no more.

The data that is returned is correct, but it is not ALL the data. As written, the test will pass but it should fail.

So the way to properly test this is to form the correct records from the raw points and then check for equality (modulo floating point rounding).

**Comment by emptyflash** [comment]
So if I understand correctly, if I used `helperCheckStatisticalCorrect` with the generated mock data (raw points) and both the flushed and unflushed query results, that cover would cover the case described? I was considering doing that initially but I wasn't sure how necessary it was.

**Comment by immesys** [comment]
No we don't want to trust the flushed data as the only check, because that
code might have a bug too. You will need to write the code that takes raw
data points and makes the list of statistical ones.

On Feb 26, 2018 3:51 PM, "Cameron Alexander" <notifications@github.com>
wrote:

So if I understand correctly, if I used helperCheckStatisticalCorrect with
the generated mock data (raw points) and both the flushed and unflushed
query results, that cover would cover the case described? I was considering
doing that initially but I wasn't sure how necessary it was.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/BTrDB/btrdb/pull/1#issuecomment-368693511>, or mute the
thread

**Comment by emptyflash** [comment]
When I say `helperCheckStatisticalCorrect` I mean the function that takes raw points and checks them against the stat points to ensure they're correct: https://github.com/BTrDB/btrdb/pull/1/files#diff-1ba2a9ce5dc3bc979e7f28e79c4cb1f0R85

So if I replaced the `helperCheckStatisticalEqual` that checks the equality of the flushed and unflushed results, and instead called `helperCheckStatisticalCorrect` with both results, that should be sufficient right?

**Comment by immesys** [comment]
I think you are still misunderstanding the problem. As written, the helperCheckStatisticalCorrect does not sufficiently check the answers. It checks that the statistical windows that ARE there are correct, but it does not check that ALL the windows are there. Do you understand the difference? At the moment, say I am supposed to get 100 windows, but I get only 1, the test will pass if that one window is correct, but the query is wrong.

**Comment by immesys** [comment]
Your new changes are on the right track. The only thing that looks off now is that a window starts at the start time of the query, not the time of the first point. So the function to make the windows needs to take the query start time as a parameter and use that rather than the first point's time as it does now.

EDIT: that is for unaligned windows. For aligned windows the start time is equal to `queryStart & ~((1<<pw)-1)` (the bottom pw bits masked out)

**Pull request merged**
